---
title: "Permits and ED"
author: "ignacio"
date: "March 30, 2017"
output: github_document
html_document:
  df_print: paged
  keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set( message=F, warning=F )

setwd("C:/Users/icps/Dropbox/3. Maxwell/3. Spring Term/5. Data Driven II/Labs/all-labs-ddmii-icps86/Permits_and_EC/")

library(dplyr)
library(spatialEco) # spatial econometrics package
library(GISTools)
library(pander)
library(ggmap)

```

```{r, echo=FALSE, eval=FALSE}
#Formatting the dataframe
dat <- read.csv("C:/Users/icps/Dropbox/3. Maxwell/3. Spring Term/5. Data Driven II/Labs/Instructions/Permits_ED/PrivateInvestment_Clean.csv", stringsAsFactors = F)

#making valuation and fee variables to be numeric
x <- dat$Valuation
x <- gsub("$", "", x, fixed = T)
x <- gsub(",", "", x, fixed = T)
x <- as.numeric(x)
dat$Valuation <- x

x <- dat$Fee.Amount
x <- gsub("$", "", x, fixed = T)
x <- gsub(",", "", x, fixed = T)
x <- as.numeric(x)
dat$Fee.Amount <- x


#Creating a variable for the year
x <- dat$Issued
x <- gsub( "\\d{2}/\\d{2}/", "", x) #deleting everything except the year. btw: "\\d{2}" means any two digits
x <- as.numeric(x)
dat$Year <- x
dat <- dat[,c(1:6,9,7,8)]
save(dat, file= "Permits.rda")
```

```{r, echo=FALSE, eval=FALSE}
#CREATING SUBSETS from the PERMITS.rda (dat) for EACH VARIABLE

load("Permits.rda")

#Found
x <- as.character(dat$Type)

df.F <- x == "Footing / Foundation"
df.F <- dat[df.F, ]

#Res
df.R <- x== "Res. Remodel/Chg Occ" | x == "Res. New 1-2 Family" 
df.R <- dat[df.R,]

#Com
df.C <- x== "Com. New Building" | x=="Com. Reno/Rem/Chg Occ"
df.C <- dat[df.C,]

#Dem
df.D <- x=="Demolition"
df.D <- dat[df.D,]

#Ins
df.I <- x=="Antenna / Dish" | x=="Electric" | x=="Electric (Meter Set)" | x=="Elevator" | x=="Fire Alarm" | x=="HVAC/Mechanical" | x=="Misc.(deck, fence,ramp)" | x=="Pool / Hot Tub" | x=="Security Alarm" | x=="Sprinkler" | x=="Tank"
df.I <- dat[df.I,]


#Ign
df.Ign <- x=="Block Party (Business)" | x=="Block Party (Residential)" | x=="Curb Cut" | x=="Encroach (Deminimus)" | x=="Encroach (Major)"  | x=="Encroachment (Converted)" | x=="Liability Waiver" | x=="Loading Zone (Business)" | x=="Parking Meter Rental" | x=="Public Assembly" | x=="Road Cut" | x=="Sidewalk Cafe" | x=="Sidewalk Replace" | x=="Sign" | x=="Site Work"
df.Ign <- dat[df.Ign,]  
save(df.Ign, file = "df.Ign.rda")

```

```{r, echo=F, eval=F}
#GEOCODING the dataframes

#devtools::install_github("dkahle/ggmap") #Installing latest ggmap from the creators webpage. Need to download this in order for the code to work.

register_google(key = "YOUR KEY HERE", account_type = "premium", day_limit = 100000) #Need to put premium to fool the function. I did not have a premium, just a google API key that was authorized to bill me
ggmap_credentials()
geocodeQueryCheck()

#in what follows I geocoded 17,933 permits in approx 3h

#Found
df.F$Location2 <- paste(df.F$Location, ", Syracuse, New York", sep = "")
df.F <- mutate_geocode(df.F, Location2, source = "google")
save(df.F, file = "df.F.rda")

#Res
df.R$Location2 <- paste(df.R$Location, ", Syracuse, New York", sep = "")
df.R <- mutate_geocode(df.R, Location2, source = "google")
save(df.R, file = "df.R.rda")

#Com
df.C$Location2 <- paste(df.C$Location, ", Syracuse, New York", sep = "")
df.C <- mutate_geocode(df.C, Location2, source = "google")
save(df.C, file = "df.C.rda")

#Dem
df.D$Location2 <- paste(df.D$Location, ", Syracuse, New York", sep = "")
df.D <- mutate_geocode(df.D, Location2, source = "google")
save(df.D, file = "df.D.rda")

#Ins
df.I$Location2 <- paste(df.I$Location, ", Syracuse, New York")
df.I <- mutate_geocode(df.I, Location2, source = "google")
save(df.I, file = "df.I.rda")

```

```{r, echo=F, eval=F}
#cLEANING ADDRESSES AND BATCH GEOCODEDING THEM

#1. CLEANING ADDRESSES
#good source for regular expressions:
#https://rstudio-pubs-static.s3.amazonaws.com/74603_76cd14d5983f47408fdf0b323550b846.html
#https://www.rstudio.com/wp-content/uploads/2016/09/RegExCheatsheet.pdf

#FOUNDATIONS
load("df.F.rda") #loading the data frame 
x <- is.na(df.F$lat)
df.Fna <- df.F[x,]

miss <- df.Fna$Location2

miss <- gsub( " R \\d{1,} .*", "", miss)
miss <- gsub( " To .*", "", miss)
miss <- paste(miss, ", Syracuse, New York", sep = "")

df.Fna$Location2 <- miss

#RESIDENTIAL
load("df.R.rda") #loading the data frame 
x <- is.na(df.R$lat)
df.Rna <- df.R[x,]

miss <- df.Rna$Location2

miss <- gsub( " , Syracuse, New York", "", miss) # removing syra
miss <- gsub( "Skytop Housing ", "", miss)
miss <- gsub( "Rear", "", miss)
miss <- gsub( " To .*", "", miss)
miss <- gsub( " & .*", "", miss)
miss <- gsub( "Scott O'Grady ", "", miss)
miss <- gsub( " R \\d{1,} .*", "", miss)
miss <- paste(miss, ", Syracuse, New York",sep = "")

df.Rna$Location2 <- miss

#COMERCIAL
load("df.C.rda") #loading the data frame 
x <- is.na(df.C$lat)
df.Cna <- df.C[x,]

miss <- df.Cna$Location2

miss <- gsub( " , Syracuse, New York", "", miss) # removing syra
miss <- gsub( "\n", "", miss)

#if content replace whole address by name of building/location
miss <- gsub( ".*Flanagan Gym.*", "Flanagan Gym", miss)
miss <- gsub( ".*Falk College.*", "Falk College", miss)
miss <- gsub( ".*Hinds Hall.*", "Hinds Hall", miss)
miss <- gsub( ".*Graham Dining Hall.*", "Graham Dining Hall", miss)
miss <- gsub( ".*Bowne Hall.*", "Bowne Hall", miss)
miss <- gsub( ".*Flint Hall.*", "Flint Hall", miss)
miss <- gsub( ".*Physics Bldg.*", "Physics Building", miss)
miss <- gsub( ".*Hendricks Chapel.*", "Hendricks Chapel", miss)
miss <- gsub( ".*1320 Jamesville Ave.*", "1320 Jamesville Ave", miss)
miss <- gsub( ".*Carousel Center.*","Carousel Center Dr", miss)
miss <- gsub( ".*Hiawatha.*","306 Hiawatha Blvd W", miss)
miss <- gsub( ".*Destiny USA Dr.*","Destiny USA Dr", miss)
miss <- gsub( ".*Airport Boulevard.*", "Airport Boulevard", miss)
miss <- gsub( ".*Bird Library.*", "Bird Library", miss)

#Delete from string
miss <- gsub( "Rear", "", miss)
miss <- gsub( "Skytop Housing ", "", miss)
miss <- gsub( "Slocum Heights ", "", miss)
miss <- gsub( "Small Rd", "", miss)
miss <- gsub( "M17 Daycare ", "", miss)
miss <- gsub( "Lambreth Ln", "", miss)
miss <- gsub( "Farm Acre Rd", "", miss)
miss <- gsub( "Chinook Dr", "", miss)
miss <- gsub( "Life Science Center", "", miss)
miss <- gsub( "Playing Fields, Courts", "", miss)
miss <- gsub( "Newhouse 1 and 2", "", miss)
miss <- gsub( "Steam & Chilled Water", "", miss)
miss <- gsub( "Physical Plan & Commissary ", "", miss)
miss <- gsub( "Scott O'Grady ", "", miss)
miss <- gsub( "Sutherland Group ", "", miss)
miss <- gsub( "Unit \\d{1,3} ", "", miss)
miss <- gsub( "Watson Hall 306-12 ", "", miss)

miss <- gsub( " To .*", "", miss)
miss <- gsub( " to .*", "", miss)
miss <- gsub( "&.*", "", miss)
miss <- gsub( "\\d{3} \\(.*\\) ", "", miss)
miss <- gsub( "^ ", "", miss)

#adding back syracuse and new york
miss <- paste(miss, ", Syracuse, New York", sep = "")

df.Cna$Location2 <- miss


#DEMOLITION
load("df.D.rda") #loading the data frame 
x <- is.na(df.D$lat)
df.Dna <- df.D[x,]

miss <- df.Dna$Location2

miss <- gsub( " , Syracuse, New York", "", miss) # removing syra
miss <- gsub( "\n", "", miss)
miss <- gsub( "Woodframe Rental ", "", miss)
miss <- gsub( "VPA East Genesee St ", "", miss)
miss <- gsub( "Rear", "", miss)
miss <- gsub( " To .*", "", miss)
miss <- gsub( " to .*", "", miss)
miss <- gsub( "&.*", "", miss)

#adding back syracuse and new york
miss <- paste(miss, ", Syracuse, New York", sep = "")

df.Dna$Location2 <- miss

#INSTALATIONS AND REPAIRS
load("df.I.rda") #loading the data frame 
x <- is.na(df.I$lat)
df.Ina <- df.I[x,]

miss <- df.Ina$Location2

#delete content in string
miss <- gsub( " , Syracuse, New York", "", miss) # removing syra
miss <- gsub( "\n", "", miss)
miss <- gsub( "Rear", "", miss)

#if content replace whole address by name of building/location
miss <- gsub( ".*Flanagan Gym.*", "Flanagan Gym", miss)
miss <- gsub( ".*Falk College.*", "Falk College", miss)
miss <- gsub( ".*Hinds Hall.*", "Hinds Hall", miss)
miss <- gsub( ".*Graham Dining Hall.*", "Graham Dining Hall", miss)
miss <- gsub( ".*Bowne Hall.*", "Bowne Hall", miss)
miss <- gsub( ".*Flint Hall.*", "Flint Hall", miss)
miss <- gsub( ".*Physics Bldg.*", "Physics Building", miss)
miss <- gsub( ".*Hendricks Chapel.*", "Hendricks Chapel", miss)
miss <- gsub( ".*1320 Jamesville Ave.*", "1320 Jamesville Ave", miss)
miss <- gsub( ".*Carousel Center.*","Carousel Center Dr", miss)
miss <- gsub( ".*Hiawatha.*","306 Hiawatha Blvd W", miss)
miss <- gsub( ".*Destiny USA Dr.*","Destiny USA Dr", miss)
miss <- gsub( ".*Airport Boulevard.*", "Airport Boulevard", miss)
miss <- gsub( ".*Bird Library.*", "Bird Library", miss)
miss <- gsub( ".*1320 Jamesville Ave.*", "1320 Jamesville Ave", miss)
miss <- gsub( ".*Archbold Gym.*", "Archbold Gym", miss)
miss <- gsub( ".*Schine Student Center.*", "Schine Student Center", miss)

#delete content in string
miss <- gsub( "Shaffer Art ", "", miss)
miss <- gsub( "Tolley Humanities Bldg ", "", miss)
miss <- gsub( "Machinery Hall ", "", miss)
miss <- gsub( "Raynor Parking Lot ", "", miss)
miss <- gsub( "Henry Parking Lot ", "", miss)
miss <- gsub( "Newhouse 1 and 2 ", "", miss)
miss <- gsub( "Watson Hall ", "", miss)
miss <- gsub( "DellPlain and Ernie Davis Hall ", "", miss)
miss <- gsub( "Academic Bldg ", "", miss)
miss <- gsub( "Playing Fields, Courts", "", miss)
miss <- gsub( "Physical Plan & Commissary ", "", miss)
miss <- gsub( "R \\d{2,3} Xavier", "", miss)
miss <- gsub( "121 (253-260) Small Rd ", "", miss)
miss <- gsub( "Skytop Housing East ", "", miss)
miss <- gsub( "Skytop Housing West ", "", miss)
miss <- gsub( "Skytop Housing ", "", miss)
miss <- gsub( "Unit \\d{1,3} ", "", miss)
miss <- gsub( "\\d{3} \\(.*\\) ", "", miss)
miss <- gsub( "160 Small Rd ", "", miss)
miss <- gsub( "Small Rd ", "", miss)
miss <- gsub( "Slocum Heights ", "", miss)
miss <- gsub( "Winding Ridge Rd ", "", miss)
miss <- gsub( "Lambreth Ln ", "", miss)
miss <- gsub( "Farm Acre Rd ", "", miss)
miss <- gsub( "Chinook Dr ", "", miss)
miss <- gsub( "M17 Daycare ", "", miss)
miss <- gsub( "norman Jemal ", "", miss)
miss <- gsub( "Life Science Center ", "", miss)
miss <- gsub( " Comm #1-3A", "", miss)
miss <- gsub( " Condo [[:alpha:]]{3,4}", "", miss)
miss <- gsub( "Scott O'Grady", "", miss)
miss <- gsub( "R \\d{2} Nursery", "", miss)
miss <- gsub( "Unit 24 Sutherland Group ", "", miss)
miss <- gsub( "Unit 18 M/E Engineering ", "", miss)
miss <- gsub( "Irving Garage and Dineen Hall ", "", miss)
miss <- gsub( "VPA East Genesee St ", "", miss)
miss <- gsub( "Haft Hall ", "", miss)
miss <- gsub( "Sutherland Group ", "", miss)
miss <- gsub( "M/E Engineering ", "", miss)
miss <- gsub( "Steam & Chilled Water", "", miss)
miss <- gsub( "Physical Plan & Commissary ", "", miss)

miss <- gsub( " To .*", "", miss)
miss <- gsub( " to .*", "", miss)
miss <- gsub( "&.*", "", miss)
miss <- gsub( "^ ", "", miss)

#adding back syracuse and new york
miss <- paste(miss, ", Syracuse, New York", sep = "")

df.Ina$Location2 <- miss





###############


#2. GEOCODING THE NAs

register_google(key = "YOUR KEY HERE", account_type = "premium", day_limit = 100000) #Need to put premium to fool the function. I did not have a premium, just a google API key that was authorized to bill me
ggmap_credentials()
geocodeQueryCheck()

#Found
df.Fna <- mutate_geocode(df.Fna, Location2, source = "google")
sum(is.na(df.Fna$lat)) #no NAs
save(df.Fna, file = "df.Fna.rda")

#Res
df.Rna <- mutate_geocode(df.Rna, Location2, source = "google")
sum(is.na(df.Rna$lat)) #1 NA

x <- is.na(df.Rna$lat)

#manually fixing last addresses
df.Rna[x,11] <- "115 Marlett St, Syracuse, New York"

#geocoding
location <- geocode(df.Rna[x,11], source = "google")

#adding lon
df.Rna[x,12] <- location[,1]

#adding lat
df.Rna[x,13] <- location[,2]

save(df.Rna, file = "df.Rna.rda")


#Com
df.Cna <- mutate_geocode(df.Cna, Location2, source = "google")
sum(is.na(df.Cna$lat)) #4 NAs

x <- is.na(df.Cna$lat)

#manually fixing last addresses
df.Cna[x,11] <- c("914-22 Genesee St E, Syracuse, New York",
                  "Schine Student Center, Syracuse, New York",
                  "605-11 Raynor Ave E, Syracuse, New York",
                  "605-11 Raynor Ave E, Syracuse, New York")

#geocoding
location <- geocode(df.Cna[x,11], source = "google")

#adding lon
df.Cna[x,12] <- location[,1]

#adding lat
df.Cna[x,13] <- location[,2]

save(df.Cna, file = "df.Cna.rda")


#Dem
df.Dna <- mutate_geocode(df.Dna, Location2, source = "google")
sum(is.na(df.Dna$lat)) #no NAs

save(df.Dna, file = "df.Dna.rda")

#Installations
df.Ina <- mutate_geocode(df.Ina, Location2, source = "google")
sum(is.na(df.Ina$lat)) #2 NAs

x <- is.na(df.Ina$lat)

#manually fixing last addresses
df.Ina[x,11] <- c("104 Mc Allister Ave, Syracuse, New York","867 Emerson Ave, Syracuse, New York")

#geocoding
location <- geocode(df.Ina[x,11], source = "google")

#adding lon
df.Ina[x,12] <- location[,1]

#adding lat
df.Ina[x,13] <- location[,2]

save(df.Ina, file = "df.Ina.rda")


########################


#Merging the NAs with the originals

#FOUND
load("df.F.rda")
dim(df.F)
x <- is.na(df.F$lat)
df.F[x,] <- df.Fna
save(df.F, file = "df.F.rda")

#RES
load("df.R.rda")
dim(df.R)
x <- is.na(df.R$lat)
sum(x)
dim(df.Rna)
df.R[x,] <- df.Rna
save(df.R, file = "df.R.rda")

#COM
load("df.C.rda")
dim(df.C)
x <- is.na(df.C$lat)
sum(x)
dim(df.Cna)
df.C[x,] <- df.Cna
save(df.C, file = "df.C.rda")

#DEM
load("df.D.rda")
dim(df.D)
x <- is.na(df.D$lat)
sum(x)
dim(df.Dna)
df.D[x,] <- df.Dna
save(df.D, file = "df.D.rda")

#INSTALLATION
load("df.I.rda")
dim(df.I)
x <- is.na(df.I$lat)
sum(x)
dim(df.Ina)
df.I[x,] <- df.Ina
save(df.I, file = "df.I.rda")

```

```{r, echo=FALSE, eval=FALSE}
#Generating the TYPES dataframe: to show the freq of the permits types

#using table to create a dataframe with the frequencies for each category
types <- data.frame(type = names(table(dat$Type)), freq = as.numeric(table(dat$Type)))
types <- types[order(types$freq, decreasing = T),]
rownames(types) <- NULL
types <- arrange(types, type) #ordering types alphabetically

#getting the mean/max/min value per type
x <- aggregate(dat$Valuation, by=list(dat$Type), FUN=mean)
x <- arrange(x, Group.1)
types$meanval <- x$x

#getting the min value per type
x <- aggregate(dat$Valuation, by=list(dat$Type), FUN=min)
x <- arrange(x, Group.1)
types$minval <- x$x

#getting the max value per type
x <- aggregate(dat$Valuation, by=list(dat$Type), FUN=max)
x <- arrange(x, Group.1)
types$maxval <- x$x

save(types, file= "types.rda")

```

```{r, echo=F}
#LOADING THE SHAPEFILES
load("shapestracts.rda") #loading the shape file with the census tracts.
shapes <- shapes[as.numeric(as.character(shapes$NAME10)) < 64, ] #Cutting all tracks that are not in syracuse. lower than 64 gets this.#DO THIS FOR  REMOVING SHAPES NOT WANTED.

#FORMATTING the DATAFRAMES into SPATIAL DATA FOR PLOTTING
#In order to do the points in poly operation, I will convert the dataframes into coordinate objects (this disables the view option in Rstudio) and I will also  specify  the value of the proj4strings (see code below... proj4string(df.F) <- CRS("+proj=longlat +datum=WGS84"))
#For more reference look at: http://r-sig-geo.2731867.n2.nabble.com/point-in-polygon-or-over-help-td7583635.html

#FOUNDATIONS
load("df.F.rda") #loading the data frame 
x <- is.na(df.F$lat)
missing <- data.frame("variable" = "Foundations", "NAs" = sum(x), row.names = NULL, stringsAsFactors = F) #creating a dataframe with the NAs for each variable
df.F <- df.F[!x,] #removing NAs
coordinates(df.F) = ~lon+lat #making it a coordinates object
proj4string(df.F) <- CRS("+proj=longlat +datum=WGS84") #fixing it 

#RESIDENTIAL
load("df.R.rda") #loading the data frame 
x <- is.na(df.R$lat)
missing[nrow(missing) + 1,] <- c("variable" = "Residential", "Nas" = sum(x))
df.R <- df.R[!x,] #removing NAs
coordinates(df.R) = ~lon+lat #making it a coordinates object
proj4string(df.R) <- CRS("+proj=longlat +datum=WGS84") #fixing it 

#COMERCIAL
load("df.C.rda") #loading the data frame 
x <- is.na(df.C$lat)
missing[nrow(missing) + 1,] <- c("variable" = "Comercial", "Nas" = sum(x))
df.C <- df.C[!x,] #removing NAs
coordinates(df.C) = ~lon+lat #making it a coordinates object
proj4string(df.C) <- CRS("+proj=longlat +datum=WGS84") #fixing it 

#DEMOLITION
load("df.D.rda") #loading the data frame 
x <- is.na(df.D$lat)
missing[nrow(missing) + 1,] <- c("variable" = "Demolition", "Nas" = sum(x))
df.D <- df.D[!x,] #removing NAs
coordinates(df.D) = ~lon+lat #making it a coordinates object
proj4string(df.D) <- CRS("+proj=longlat +datum=WGS84") #fixing it 

#INSTALATIONS AND REPAIRS
load("df.I.rda") #loading the data frame 
x <- is.na(df.I$lat)
missing[nrow(missing) + 1,] <- c("variable" = "Int and Rep", "Nas" = sum(x))
df.I <- df.I[!x,] #removing NAs
coordinates(df.I) = ~lon+lat #making it a coordinates object
proj4string(df.I) <- CRS("+proj=longlat +datum=WGS84") #fixing it 

#IGNORED
load("df.Ign.rda")
```


###PROPOSED INDICATORS

```{r, echo=FALSE}
#loading the types dataframe and creating an index of the types to run the following code chunks
load("types.rda")
x<- as.character(types$type)

```

###**1.New Foundations starts (Found)**
```{r, echo=FALSE}
Found <- x == "Footing / Foundation"
Found <- types[Found, ]
pander(Found)
pander(table(df.F$Year))
summary(df.F$Valuation) %>% pander
barplot(sort(df.F$Valuation, decreasing = T))

plot(shapes
     , axes = T
     ) 
  title(main = "Foundation starts Permits")
  points(df.F, pch=20, cex = 1.2, col=adjustcolor("deeppink4", alpha.f = 1))


```

###**2.New/Reno Residential (Res)**
```{r, echo=FALSE}
Res <- x== "Res. Remodel/Chg Occ" | x == "Res. New 1-2 Family" 
Res <- types[Res,]
pander(Res)
pander(table(df.R$Year))
summary(df.R$Valuation) %>% pander
barplot(sort(df.R$Valuation, decreasing = T))

#plotting Residential 
plot(shapes
     , axes = T
     ) 
  title(main = "Residential Permits")
  points(df.R, pch=20, cex = .4, col=adjustcolor("dodgerblue4", alpha.f = .8))

```

###**3.New/Reno Commercial (Com)**
```{r, echo=FALSE}
Com <- x== "Com. New Building" | x=="Com. Reno/Rem/Chg Occ"
Com <- types[Com,]
pander(Com)
pander(table(df.C$Year))
summary(df.C$Valuation) %>% pander
barplot(sort(df.C$Valuation, decreasing = T))

plot(shapes
     , axes = T
     ) 
title(main = "Residential and commercial Permits")
points(df.C, pch=20, cex= .2, col=adjustcolor("firebrick", alpha.f = .8))


```

###**4.Demolitions (Dem)**
```{r, echo=FALSE}
Dem <- x=="Demolition"
Dem <- types[Dem,]
pander(Dem)
pander(table(df.D$Year))
summary(df.D$Valuation) %>% pander
barplot(sort(df.D$Valuation, decreasing = T))

plot(shapes
     , axes = T
     ) 
title(main = "Demolition Permits")
points(df.D, pch=20, cex= .2, col=adjustcolor("forestgreen", alpha.f = .8))


```

###**5.Installations and Repairs (Ins)**
```{r, echo=FALSE}
Ins <- x=="Antenna / Dish" | x=="Electric" | x=="Electric (Meter Set)" | x=="Elevator" | x=="Fire Alarm" | x=="HVAC/Mechanical" | x=="Misc.(deck, fence,ramp)" | x=="Pool / Hot Tub" | x=="Security Alarm" | x=="Sprinkler" | x=="Tank"
Ins <- types[Ins,]
pander(Ins)
pander(table(df.I$Year))
summary(df.I$Valuation) %>% pander
barplot(sort(df.I$Valuation, decreasing = T))

plot(shapes
     , axes = T
     ) 
title(main = "Instalations and Repairs")
points(df.I, pch=20, cex= .2, col=adjustcolor("gold1", alpha.f = .6))

```

###**Ignored (Ign)**
```{r, echo=FALSE}
Ign <- x=="Block Party (Business)" | x=="Block Party (Residential)" | x=="Curb Cut" | x=="Encroach (Deminimus)" | x=="Encroach (Major)"  | x=="Encroachment (Converted)" | x=="Liability Waiver" | x=="Loading Zone (Business)" | x=="Parking Meter Rental" | x=="Public Assembly" | x=="Road Cut" | x=="Sidewalk Cafe" | x=="Sidewalk Replace" | x=="Sign" | x=="Site Work"
Ign <- types[Ign,]  
pander(Ign)
pander(table(df.Ign$Year))
paste("total cases:", nrow(df.Ign))
summary(df.Ign$Valuation) %>% pander
barplot(sort(df.Ign$Valuation, decreasing = T))

```

###**All together**
```{r, echo=F}

plot(shapes
     , axes = T
     ) 
  title(main = "All points")
  points(df.I, pch=20, cex= .2, col=adjustcolor("gold1", alpha.f = .6))
  points(df.C, pch=20, cex= .2, col=adjustcolor("firebrick", alpha.f = .5))
  points(df.R, pch=20, cex = .4, col=adjustcolor("dodgerblue4", alpha.f = .5))
  points(df.D, pch=20, cex = .4, col=adjustcolor("deeppink4", alpha.f = 7))
  points(df.F, pch=20, cex= 1.2, col=adjustcolor("forestgreen", alpha.f = 1))
  

```


###NAs in the data per variables

```{r, echo=F}
missing[nrow(missing)+1,] <- c("Ignored", "0")
missing %>% pander

```

