---
title: "Lab 1 - DDM2"
author: "ignacio"
date: "February 1, 2017"
output: github_document
html_document:
  df_print: paged
  keep_md: true

---

```{r setup, include=FALSE}
knitr::opts_chunk$set( message=F, warning=F )
```


```{r, echo=F, warning=F, message=F }
library(dplyr)
library(pander)
library(knitr)
library(ggmap)
library(ggplot2)
```


```{r}
#uploading the dataset
dat <- read.csv("https://raw.githubusercontent.com/lecy/code-orange/master/data/code%20violations.csv"
                 , header = TRUE
                 , stringsAsFactors = FALSE)

#Selecting columns: used colnames(dat) to find out which are the indexes i need
dat <- dat[,c(7,3,14,15)]

#converting the date from character to date type
dat$Violation.Date <- as.Date( dat$Violation.Date, format="%m/%d/%Y" )

#Creating new variables in the DF to manage dates

#1.YEAR as ordered factor
as.year <- format( dat$Violation.Date, format="%Y")
as.year <- factor(as.year,ordered=TRUE)
dat$year <- as.year

#2. MONTH as ordered factor
#we begin by making a vector 
m <- c("Ene.", "Feb.",  "Mar.", "Abr.", "May.", "Jun.", "Jul.", "Ago.", "Set.", "Oct.", "Nov.", "Dic.")
#create a factor using the vector m as the levels
as.month <- format( dat$Violation.Date, "%b" )
as.month <- factor( as.month, ordered=TRUE, levels=m )
table( as.month )[1:6] %>% pander
#adding this vector to the dataframe
dat$month <- as.month

#3. WEEK as ordered factor
as.week <- format( dat$Violation.Date, format="%W")
as.week <- factor( as.week, ordered=T)
dat$week <- as.week

#4. Day of the week as ordered factor
m <- c("lun.", "mar.", "mi?.", "jue.","vie.", "s?b.", "dom.")
as.day <- format( dat$Violation.Date, format="%a" )
as.day <- factor( as.day, ordered=TRUE, levels=m )
dat$day <-as.day


#Selecting the top 10  complain types
these <- names( sort( table( dat$Complaint.Type ), decreasing=T )[1:10] )
dat <- dat[ dat$Complaint.Type %in% these , ]

#changing them from characer to factor
dat$Complaint.Type <- as.factor( dat$Complaint.Type )

#changing the names of the levels
levels( dat$Complaint.Type )
new.labels <- c("Bed Bugs","No Permit","General","Fire Hazard",
                "Illegal Trash","Infestation","Overgrown","Exterior Maintenance",
                "Interior Maintenance","Trash")
levels( dat$Complaint.Type ) <- new.labels

```

```{r}
#creating a subdata set for only illegal trash outs.
trash <- dat[ dat$Complaint.Type == "Illegal Trash" , ]
#levels(trash$year)

#eliminating unecesary factors
trash$year <- factor(trash$year)

table(trash$year)

#per year
trash.y <- tapply(trash$year
                     , list(year= trash$year)
                     , length)
#barplot comparing years
barplot(trash.y, beside = T)

#per year and month
trash.y.m <- tapply(trash$year
                     , list(month= trash$month, 
                            year= trash$year)
                     , length)
#barplot comparing years
barplot(trash.y.m, beside = T)


#looking for months in all years

trash.ym <- format( trash$Violation.Date, "%Y-%m" )

plot(table(trash.ym), lty=3, lwd=3, las=2, cex.axis=0.5, yaxt="n", ylab="")

#day in all months and years
trash.ymd <- format( trash$Violation.Date, "%Y-%m-%d" )
#table(trash.ymd)
barplot(table(trash.ymd), cex.axis=5, yaxt="n", ylab="")


#selecting year 2012
trash2012 <- trash[ trash$year == "2012" , ]
trash2012$year <- factor(trash2012$year)
table(trash2012$year)

barplot(table(trash$month), las=1,ylab="")
mtext("Year 2012")


#removing latitudes and lon that are out of the map of syr
syr <- get_map( location="syracuse", zoom=13, maptype = "toner-lite")
ggmap( syr ) 

syr.min.lat <-  42.96
syr.max.lat <-  43.12
syr.min.lon <- -76.25
syr.max.lon <- -76.05

trash2012 <- trash2012[ trash2012$lat > syr.min.lat & trash2012$lat < syr.max.lat , ]
trash2012 <- trash2012[ trash2012$lon > syr.min.lon & trash2012$lon < syr.max.lon , ]

#the creation of a map
qmplot( lon, lat, data = trash2012, maptype="toner-lite", color=I("red"), alpha=0.3 ) + theme(legend.position="none")

#using facet wrap to output lots maps per month
qmplot( lon, lat, data = trash2012, maptype = "toner-lite", 
        color = I("orange") ) + facet_wrap(~ month )

```

